server:
  port: 8081
  servlet:
    context-path: /manager
#spring
spring:
  #DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/local?characterEncoding=UTF-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #指定数据源类型
    #type:
  #thymeleaf
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
mybatis:
  #指定pojo所在的包
  type-aliases-package: com.cl.bean
  #指定mapper的xml映射文在所在位置
  mapper-locations: classpath:com/cl/mappers/*.xml






